# Generated by Django 4.2.3 on 2024-03-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ytdl", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="video",
            options={"verbose_name": "ویدیو", "verbose_name_plural": "ویدیو ها"},
        ),
        migrations.AddField(
            model_name="video",
            name="discription",
            field=models.TextField(blank=True, null=True, verbose_name="توضیحات"),
        ),
        migrations.AddField(
            model_name="video",
            name="link",
            field=models.TextField(blank=True, null=True, verbose_name="لینک دانلود"),
        ),
        migrations.AddField(
            model_name="video",
            name="title",
            field=models.CharField(
                blank=True, max_length=580, null=True, verbose_name="نام ویدیو"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="ytdl/video/", verbose_name="ویدیو"
            ),
        ),
    ]
