# Generated by Django 4.2.3 on 2024-03-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ytdl", "0002_alter_video_options_video_discription_video_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="link",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="ytdl/video/",
                verbose_name="لینک دانلود",
            ),
        ),
    ]
